spring:
  application:
    name: main-service

  sql:
    init:
      mode: never # Не использовать schema.sql/data.sql

  liquibase:
    enabled: true # Включить Liquibase
    change-log: classpath:db/changelog/db.changelog-master.yaml

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${MAIN_DB_HOST:localhost}:${MAIN_DB_PORT:6433}/${MAIN_DB_NAME:main-service}
    username: ${MAIN_DB_USER:test}
    password: ${MAIN_DB_PASSWORD:test}

  jpa:
    hibernate:
      ddl-auto: validate # Только проверять соответствие Entity и БД

    database-platform: org.hibernate.dialect.PostgreSQLDialect

    properties:
      hibernate:
        default_schema: main # Hibernate работает со схемой main
        format_sql: true      # Красивый вывод SQL

    show-sql: true # Показывать SQL в логах

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# ---------- Eureka ----------
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${random.value}

# ---------- HTTP ----------
server:
  port: 8080
# port: 0 # Для локального запуска нескольких экземпляров из IDE
