spring:
  application:
    name: analyzer

  # Настройки Eureka клиента
eureka:
  instance:
    # Использовать IP вместо имени хоста (решает проблему с DNS)
    prefer-ip-address: true
    # Явно задаем формат ID, чтобы там был IP, а не имя хоста
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${random.value}

server:
  port: 0