CREATE SCHEMA IF NOT EXISTS main;

-- убрал привязку у таблице User requester_id
CREATE TABLE IF NOT EXISTS participation_requests
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requester_id BIGINT NOT NULL,
    event_id BIGINT NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR(20) NOT NULL,

    --CONSTRAINT fk_event1 FOREIGN KEY (event_id) REFERENCES events (id),
    CONSTRAINT chk_status CHECK (status IN ('PENDING', 'CONFIRMED', 'REJECTED', 'CANCELED'))
);

-- убрал привязку у таблице User user_id
CREATE TABLE IF NOT EXISTS comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    text TEXT NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR(20) DEFAULT 'PUBLISHED' NOT NULL,

    --CONSTRAINT fk_comment_event FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE CASCADE,
    --CONSTRAINT fk_comment_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT chk_comment_status CHECK (status IN ('PUBLISHED', 'EDITED', 'DELETED')),
    CONSTRAINT chk_comment_text CHECK (LENGTH(TRIM(text)) >= 1 AND LENGTH(text) <= 2000)
);

--     CREATE INDEX IF NOT EXISTS idx_comments_event_id ON comments(event_id);
--     CREATE INDEX IF NOT EXISTS idx_comments_user_id ON comments(user_id);
--     CREATE INDEX IF NOT EXISTS idx_comments_created_at ON comments(created_at DESC);
--     CREATE INDEX IF NOT EXISTS idx_comments_event_created ON comments(event_id, created_at DESC);
