CREATE SCHEMA IF NOT EXISTS main;

CREATE TABLE IF NOT EXISTS comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    text TEXT NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR(20) DEFAULT 'PUBLISHED' NOT NULL,
    CONSTRAINT chk_comment_status CHECK (status IN ('PUBLISHED', 'EDITED', 'DELETED')),
    CONSTRAINT chk_comment_text CHECK (LENGTH(TRIM(text)) >= 1 AND LENGTH(text) <= 2000)
);

CREATE INDEX idx_event_id ON comments (event_id);
CREATE INDEX idx_user_id ON comments (user_id);
CREATE INDEX idx_status ON comments (status);
CREATE INDEX idx_created_at ON comments (created_at);
CREATE INDEX idx_updated_at ON comments (updated_at);
