// Объявление пространства имен для организации структуры проекта
// ru.practicum.ewm.stats.avro - путь к пакету в проекте
@namespace("ru.practicum.ewm.stats.avro")

// Определение протокола (интерфейса), который содержит структуры данных
protocol UserActionProtocol {

    // Перечисление возможных типов действий пользователя
    enum ActionTypeAvro {
        VIEW,    // Просмотр мероприятия
        REGISTER,// Регистрация на мероприятие
        LIKE     // лайк мероприятия
    }

    // Структура данных для хранения информации о действии пользователя
    record UserActionAvro {
        long userId;        // Уникальный идентификатор пользователя (целое число)
        long eventId;       // Уникальный идентификатор мероприятия (целое число)
        ActionTypeAvro actionType; // Тип действия из перечисления ActionTypeAvro
        timestamp_ms timestamp;    // Временная метка в миллисекундах когда произошло действие
    }
}
